# K-Fold Cross Validation

In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [20]:
lr = LogisticRegression(max_iter=200)
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

0.9148580968280468

In [8]:
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.987037037037037

In [9]:
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9722222222222222

Now let's try K-Fold..

In [11]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3) # number of folds we want..
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [12]:
for train_index, test_index in kf.split([0,1,2,3,4,5,6,7,8]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [14]:
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train,y_train)
    return model.score(x_test, y_test)

In [22]:
get_score(LogisticRegression(max_iter=200), x_train, x_test, y_train, y_test)

0.9148580968280468

In [16]:
get_score(SVC(), x_train, x_test, y_train, y_test)

0.987037037037037

In [17]:
get_score(RandomForestClassifier(), x_train, x_test, y_train, y_test)

0.9722222222222222

Now Using Stratified K Fold as it divides each classification category in uniform way(Better)

In [18]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [38]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index,test_index in kf.split(digits.data):
    x_train, x_test, y_train, y_test = digits.data[train_index],digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(max_iter=200), x_train, x_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), x_train, x_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=20), x_train, x_test, y_train, y_test))

In [40]:
scores_l

[0.9248747913188647, 0.9432387312186978, 0.9148580968280468]

In [42]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [39]:
scores_rf

[0.9382303839732888, 0.9365609348914858, 0.9232053422370617]

The whole big thing we wrote above is for understanding..we need not to write this big loop everytime and we can instead call cross_val_score method.

In [43]:
from sklearn.model_selection import cross_val_score

In [54]:
cross_val_score(LogisticRegression(max_iter=200), digits.data, digits.target, cv=10)##cv decides the number of folds..default is 5.

array([0.90555556, 0.95      , 0.88888889, 0.92777778, 0.93888889,
       0.96111111, 0.94444444, 0.94413408, 0.87150838, 0.93854749])

In [47]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [61]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)

array([0.92777778, 0.88055556, 0.96657382, 0.96100279, 0.91922006])